services:
  _defaults:
    autowire: true
    autoconfigure: true

  JoliCode\Elastically\Transport\HttpClientTransport: ~
  JoliCode\Elastically\Messenger\IndexationRequestHandler: ~
  JoliCode\Elastically\Client:
    arguments:
      $config:
        host: '%env(ELASTICSEARCH_HOST)%'
        port: '%env(ELASTICSEARCH_PORT)%'
        transport: '@JoliCode\Elastically\Transport\HttpClientTransport'
        elastically_mappings_directory: '%kernel.project_dir%/config/elasticsearch'
        elastically_index_class_mapping:
          post: App\Model\Post
        elastically_serializer: '@serializer'
        elastically_bulk_size: 100
      $logger: '@logger'

  JoliCode\Elastically\Messenger\DocumentExchangerInterface:
    alias: App\Elasticsearch\DocumentExchanger

framework:
  messenger:
    transports:
      async: "%env(MESSENGER_TRANSPORT_DSN)%"

    routing:
      # async is whatever name you gave your transport above
      'JoliCode\Elastically\Messenger\IndexationRequest':  async