version: '3'

services:
  database:
    container_name: database
    build:
      context: ./docker/database
    environment:
      - MYSQL_DATABASE=${DATABASE_NAME}
      - MYSQL_USER=${DATABASE_USER}
      - MYSQL_PASSWORD=${DATABASE_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DATABASE_ROOT_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - ./docker/database/init.sql:/docker-entrypoint-initdb.d/init.sql:z
      - ./docker/database/data:/var/lib/mysql:z
  php-fpm:
    container_name: php-fpm
    build:
      context: ./docker/php-fpm
    depends_on:
      - database
    environment:
      - APP_ENV=${APP_ENV}
      - APP_SECRET=${APP_SECRET}
      - DATABASE_URL=mysql://${DATABASE_USER}:${DATABASE_PASSWORD}@database:3306/${DATABASE_NAME}?serverVersion=mariadb-10.4.11
    volumes:
      - .:/var/www:z
  nginx:
    container_name: nginx
    build:
      context: ./docker/nginx
    depends_on:
      - php-fpm
    volumes:
      - ./:/var/www:z
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:z
      - ./docker/nginx/sites/:/etc/nginx/sites-available:z
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d:z
      - ./docker/logs:/var/log:z
    ports:
      - "80:80"
      - "443:443"